[WIP] add helm chart for datafuse
datafuselabs/datafuse pull request #253
Opened 2021-04-06 13:50 UTC by tlightsky

## Summary

Adding a helm chart to deploy datafuse to k8s, 

## Changelog

-Build/Testing/Packaging Improvement

## Test Plan

run
`make helm` and use mysql to connect to the NodePort

2021-04-06 16:23 UTC, tlightsky commented
could try
https://tanka.dev/tutorial/jsonnet

2021-04-07 00:58 UTC, tlightsky commented
after build new master locally,
I can see info logs now,
still try to figure out how to connect to the k8s NodePort:
```
[2021-04-07T00:43:40Z INFO fuse_query] Config { version: "0.1.0-ce9a196 (2021-04-06)", log_level: "info", num_cpus: 6, mysql_handler_host: "127.0.0.1", mysql_handler_port: 3307, mysql_handler_thread_num: 256, clickhouse_handler_host: "127.0.0.1", clickhouse_handler_port: 9000, clickhouse_handler_thread_num: 256, rpc_api_address: "127.0.0.1:9090", http_api_address: "127.0.0.1:8080", metric_api_address: "127.0.0.1:7070", storage_api_address: "127.0.0.1:6060" }
[2021-04-07T00:43:40Z INFO fuse_query] FuseQuery v-0.1.0-ce9a196 (2021-04-06)
[2021-04-07T00:43:40Z INFO fuse_query] MySQL handler listening on 127.0.0.1:3307, Usage: mysql -h127.0.0.1 -P3307
[2021-04-07T00:43:40Z INFO fuse_query] ClickHouse handler listening on 127.0.0.1:9000, Usage: clickhouse-client --host 127.0.0.1 --port 9000
[2021-04-07T00:43:40Z INFO fuse_query] Metric API server listening on 127.0.0.1:7070
[2021-04-07T00:43:40Z INFO fuse_query] HTTP API server listening on 127.0.0.1:7070
[2021-04-07T00:43:40Z INFO fuse_query] RPC API server listening on 127.0.0.1:9090
[2021-04-07T00:43:40Z INFO warp::server] Server::run; addr=127.0.0.1:8080
[2021-04-07T00:43:40Z INFO warp::server] listening on http://127.0.0.1:8080
```

```
❯ k describe service datafuse                       
Name:                     datafuse
Namespace:                default
Labels:                   app.kubernetes.io/instance=datafuse
                          app.kubernetes.io/managed-by=Helm
                          app.kubernetes.io/name=datafuse
                          app.kubernetes.io/version=1.16.0
                          helm.sh/chart=datafuse-0.1.0
Annotations:              meta.helm.sh/release-name: datafuse
                          meta.helm.sh/release-namespace: default
Selector:                 app.kubernetes.io/instance=datafuse,app.kubernetes.io/name=datafuse
Type:                     NodePort
IP:                       10.111.240.191
LoadBalancer Ingress:     localhost
Port:                     mysql  3307/TCP
TargetPort:               3307/TCP
NodePort:                 mysql  31484/TCP
Endpoints:                10.1.1.56:3307
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

2021-04-07 19:08 UTC, ZhiHanZ commented
Could you write a simple README file on helm charts related things like how to run the whole things, env settings and so on

2021-04-08 02:15 UTC, tlightsky commented
got it,
I'll add some info around here:
https://github.com/datafuselabs/datafuse/blob/master/docs/overview/building-and-running.md#L50-L50

2021-04-08 07:10 UTC, tlightsky commented
Hi @ZhiHanZ,
added the README info

2021-04-08 08:18 UTC, ZhiHanZ requested changes

2021-04-08 08:18 UTC, ZhiHanZ commented on charts/datafuse/templates/hpa.yaml
> +kind: HorizontalPodAutoscaler
In alpha stage, it is fine, I am worrying about its behavior may incur flaky issues in production environment, maybe we could consider to use keda.sh in future release

2021-04-08 08:18 UTC, ZhiHanZ commented on charts/datafuse/templates/service.yaml
> +    - port: 3307
again, use .Values port instead of hard coded one

2021-04-08 08:18 UTC, ZhiHanZ commented on docs/overview/building-and-running.md
> +### 4.1 Dependencies
should add helm link and supported k8s versions

2021-04-09 03:50 UTC, BohuTANG approved these changes

2021-04-09 03:51 UTC, BohuTANG commented
Very Cool.
Thanks you @tlightsky

2021-04-09 03:51 UTC, merged

2021-04-12 06:50 UTC, tlightsky commented
all comment fixed here: https://github.com/datafuselabs/datafuse/pull/298