[WIP] Constant Folding
datafuselabs/datafuse pull request #564
Opened 2021-05-17 15:13 UTC by jyizheng

## Summary

Implement constant folding

## Changelog

- New Feature

## Related Issues

Fixes #433 

## Test Plan

Unit Tests
Stateless Tests

2021-05-23 03:54 UTC, jyizheng commented
We probably need to fix issue #598 and #597 to fully implement constant folding.
Is it okay to review and merge the current code?

2021-05-26 11:07 UTC, BohuTANG commented
If the PR is ready, please click `Ready for review` and trigger the reviewers.

2021-05-26 11:42 UTC, sundy-li requested changes

2021-05-28 01:31 UTC, sundy-li approved these changes
LGTM

2021-05-28 01:32 UTC, merged